// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: split_the_bill.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BillStake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	P      uint64 `protobuf:"varint,2,opt,name=p,proto3" json:"p,omitempty"`
	Q      uint64 `protobuf:"varint,3,opt,name=q,proto3" json:"q,omitempty"`
}

func (x *BillStake) Reset() {
	*x = BillStake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_split_the_bill_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillStake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillStake) ProtoMessage() {}

func (x *BillStake) ProtoReflect() protoreflect.Message {
	mi := &file_split_the_bill_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillStake.ProtoReflect.Descriptor instead.
func (*BillStake) Descriptor() ([]byte, []int) {
	return file_split_the_bill_proto_rawDescGZIP(), []int{0}
}

func (x *BillStake) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BillStake) GetP() uint64 {
	if x != nil {
		return x.P
	}
	return 0
}

func (x *BillStake) GetQ() uint64 {
	if x != nil {
		return x.Q
	}
	return 0
}

type BillItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title  string       `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Price  int64        `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Type   int64        `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Stakes []*BillStake `protobuf:"bytes,4,rep,name=stakes,proto3" json:"stakes,omitempty"`
}

func (x *BillItem) Reset() {
	*x = BillItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_split_the_bill_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillItem) ProtoMessage() {}

func (x *BillItem) ProtoReflect() protoreflect.Message {
	mi := &file_split_the_bill_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillItem.ProtoReflect.Descriptor instead.
func (*BillItem) Descriptor() ([]byte, []int) {
	return file_split_the_bill_proto_rawDescGZIP(), []int{1}
}

func (x *BillItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BillItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BillItem) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BillItem) GetStakes() []*BillStake {
	if x != nil {
		return x.Stakes
	}
	return nil
}

type BillShare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Value  int64 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *BillShare) Reset() {
	*x = BillShare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_split_the_bill_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillShare) ProtoMessage() {}

func (x *BillShare) ProtoReflect() protoreflect.Message {
	mi := &file_split_the_bill_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillShare.ProtoReflect.Descriptor instead.
func (*BillShare) Descriptor() ([]byte, []int) {
	return file_split_the_bill_proto_rawDescGZIP(), []int{2}
}

func (x *BillShare) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BillShare) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SplitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items  []*BillItem  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Shares []*BillShare `protobuf:"bytes,2,rep,name=shares,proto3" json:"shares,omitempty"`
}

func (x *SplitRequest) Reset() {
	*x = SplitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_split_the_bill_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SplitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitRequest) ProtoMessage() {}

func (x *SplitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_split_the_bill_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitRequest.ProtoReflect.Descriptor instead.
func (*SplitRequest) Descriptor() ([]byte, []int) {
	return file_split_the_bill_proto_rawDescGZIP(), []int{3}
}

func (x *SplitRequest) GetItems() []*BillItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SplitRequest) GetShares() []*BillShare {
	if x != nil {
		return x.Shares
	}
	return nil
}

type SplitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SplitResponse) Reset() {
	*x = SplitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_split_the_bill_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SplitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitResponse) ProtoMessage() {}

func (x *SplitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_split_the_bill_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitResponse.ProtoReflect.Descriptor instead.
func (*SplitResponse) Descriptor() ([]byte, []int) {
	return file_split_the_bill_proto_rawDescGZIP(), []int{4}
}

func (x *SplitResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_split_the_bill_proto protoreflect.FileDescriptor

var file_split_the_bill_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x5f, 0x74, 0x68, 0x65, 0x5f, 0x62, 0x69, 0x6c, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x09, 0x42, 0x69, 0x6c, 0x6c, 0x53, 0x74,
	0x61, 0x6b, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x70, 0x12, 0x0c, 0x0a, 0x01, 0x71, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x01, 0x71, 0x22, 0x6e, 0x0a, 0x08, 0x42, 0x69, 0x6c, 0x6c,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x6b, 0x65,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x09, 0x42, 0x69, 0x6c, 0x6c,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x53, 0x0a, 0x0c, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x22, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x22, 0x1f, 0x0a, 0x0d, 0x53, 0x70, 0x6c,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x32, 0x44, 0x0a, 0x13, 0x53, 0x70,
	0x6c, 0x69, 0x74, 0x54, 0x68, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x2d, 0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x42, 0x69, 0x6c, 0x6c, 0x53, 0x70, 0x6c, 0x69,
	0x74, 0x12, 0x0d, 0x2e, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0e, 0x2e, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x47, 0x42, 0x11, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x54, 0x68, 0x65, 0x42, 0x69, 0x6c, 0x6c,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x6c, 0x61, 0x6d, 0x4a, 0x61, 0x6d, 0x2f, 0x64, 0x6f, 0x6c, 0x67,
	0x6f, 0x76, 0x6e, 0x79, 0x61, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_split_the_bill_proto_rawDescOnce sync.Once
	file_split_the_bill_proto_rawDescData = file_split_the_bill_proto_rawDesc
)

func file_split_the_bill_proto_rawDescGZIP() []byte {
	file_split_the_bill_proto_rawDescOnce.Do(func() {
		file_split_the_bill_proto_rawDescData = protoimpl.X.CompressGZIP(file_split_the_bill_proto_rawDescData)
	})
	return file_split_the_bill_proto_rawDescData
}

var file_split_the_bill_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_split_the_bill_proto_goTypes = []interface{}{
	(*BillStake)(nil),     // 0: BillStake
	(*BillItem)(nil),      // 1: BillItem
	(*BillShare)(nil),     // 2: BillShare
	(*SplitRequest)(nil),  // 3: SplitRequest
	(*SplitResponse)(nil), // 4: SplitResponse
}
var file_split_the_bill_proto_depIdxs = []int32{
	0, // 0: BillItem.stakes:type_name -> BillStake
	1, // 1: SplitRequest.items:type_name -> BillItem
	2, // 2: SplitRequest.shares:type_name -> BillShare
	3, // 3: SplitTheBillService.NewBillSplit:input_type -> SplitRequest
	4, // 4: SplitTheBillService.NewBillSplit:output_type -> SplitResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_split_the_bill_proto_init() }
func file_split_the_bill_proto_init() {
	if File_split_the_bill_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_split_the_bill_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillStake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_split_the_bill_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_split_the_bill_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillShare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_split_the_bill_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SplitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_split_the_bill_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SplitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_split_the_bill_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_split_the_bill_proto_goTypes,
		DependencyIndexes: file_split_the_bill_proto_depIdxs,
		MessageInfos:      file_split_the_bill_proto_msgTypes,
	}.Build()
	File_split_the_bill_proto = out.File
	file_split_the_bill_proto_rawDesc = nil
	file_split_the_bill_proto_goTypes = nil
	file_split_the_bill_proto_depIdxs = nil
}
